language: php

php:
  - 7.4
  - 8.1

env:
  matrix:
    - TYPO3_VERSION=^10.4 TESTING_VERSION=6.x-dev
    - TYPO3_VERSION=^11.5 TESTING_VERSION=7.x-dev

matrix:
  exclude:
  - php: 7.4
    env: TYPO3_VERSION=^11.5 TESTING_VERSION=7.x-dev

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/minimal=$TYPO3_VERSION
  - composer require typo3/testing-framework=$TESTING_VERSION
  # Restore composer.json
  - git checkout composer.json

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit .Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml --colors=never Tests/Unit/
